import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>내일부터 진짜 한다</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>내일부터 진짜 한다</h1>

        <p>
          먼저{" "}
          <Link href="/Login">
            <u>로그인</u>
          </Link>{" "}
          해주세요!
        </p>
      </main>
    </>
  );
};

export default Home;
